// src/views/prizes/components/PrizesRule.vue
<template>
  <div id="prizes-rule" class="prizes-rule">
    <div class="rule-title">Terms and Conditions</div>
    <div class="prizes-rule-card">
      <div v-for="(item, index) in ruleList" :key="index">
        <div class="card-label">{{ item.label }}</div>
        <div v-if="item.image" class="image">
          <img :src="require(`../../../assets/prizes/${item.image}`)" alt="" />
        </div>
        <div
          class="card-rule-text"
          v-for="(option, idx) in item.text"
          :key="idx"
          v-html="option"
        ></div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'PrizesRule',
  data() {
    return {
      ruleList: [
        {
          label: '1.Which networks are participating in this event?',
          text: [
            '- <span class="orbiter_global_prizes_rule_tag">Bridge from specific networks to Optimism Superchain.</span>',
            '- Optimism Superchain includes: Optimism, Base, Mode, Cyber, Bob, Mint, Kroma, Lisk',
            '- Specific Chains include: Ethereum, Arbitrum, linea,scroll,zkSync Lite, Polygon, Loopring, zkSyncEra, BNB Chain, Arbitrum Nova, Mantle, opBNB, X Layer, Manta, zkFair, Blast, zkLink Nova, Proof of Play Apex, BEVM, Core, Bitlayer, BounceBit, Optopia, AlienxChain, Fraxtal, Zircuit, Fuse',
            '1.1 Which networks are added  in Extended Session?',
            '- Bridge from specific networks to Scroll Chain or bridge from Scroll Chain to specific networks.',
            '-Specific networks include: Ethereum, Arbitrum, linea,scroll,zkSync Lite, Polygon, Loopring, zkSyncEra, BNB Chain, Arbitrum Nova, Mantle, opBNB, X Layer, Zora, Manta, zkFair, Blast, zkLink Nova, Proof of Play Apex, BEVM, Core, Bitlayer, BounceBit, Optopia, AlienxChain, Fraxtal, Zircuit, Fuse, Optimism, Base, Mode, Cyber, Bob, Mint, Kroma, Lisk, Zora',
            '- The minimum amount required: 0.03 ETH',
            '- Bridge token: ETH',
          ],
        },
        {
          label:
            '2.How to share the prize pool and extra bonus?',
          text: [
            '- Complete <span class="orbiter_global_prizes_rule_tag">≥3 transactions </span> to qualify for a share of the prize pool.',
            '- <span class="orbiter_global_prizes_rule_tag">Prize Pool Breakdown:</span>',
            '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- <span class="orbiter_global_prizes_rule_tag">≥3 TX Traders:</span> Share 40% of the prize pool.',
            '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- <span class="orbiter_global_prizes_rule_tag">Top 9-100 Traders (with ≥20 TX):</span> Share 35% of the prize pool.',
            '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- <span class="orbiter_global_prizes_rule_tag">Top 1-8 Traders (with ≥20 TX):</span> Share 25% of the prize pool.',
            '- The ranking is determined based on transactions. If users have the same number of transactions, ranking will be based on the transaction value. More transactions, greater chance to win!',
            '- <span class="orbiter_global_prizes_rule_tag">Extra bonus: </span>',
            '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- <span class="orbiter_global_prizes_rule_tag">Rank in the top 5 fastest traders daily (Bridge at least 3000 TXs daily): </span> earn a 200 $USDC daily bonus.',
            '- In Tier 1 - Tier 5: An address can receive a maximum extra bonus of <span class="orbiter_global_prizes_rule_tag">3,000  $USDC</span>.',
            '- In Extended Session: An address can receive a maximum extra bonus of <span class="orbiter_global_prizes_rule_tag">1,600 $USDC</span>.',
            '- The ranking is determined based on transactions and daliy completed time. If users have the same number of transactions within the same time frame, ranking will be based on the transactions. More transactions, greater chance to win!',
            '- Note: ',
            '- We have allocated $23,000 as a total extra bonus for the top 5 fastest traders daily. Only users who meet the requirement of bridging at least 3,000 transactions (TXs) daily will be eligible for the extra bonus. If the number of users who qualify for the reward does not reach 5 per day, the rewards will not be fully distributed.'
          ],
        },
        {
          label:
            '3.What are the rules of different prize pool tiers and bridging fee rebates?',
          image: 'rule.png',
          text: [
            '<span class="orbiter_global_prizes_rule_tag">Note:</span>',
            'In Tiers 1~5:',
            '- The prize pool will be unlocked when the amount of transactions (TX) ≥ 4,000;',
            '- TOP 1 to 8 users, up to 96% bridging fees (except for gas fees) will be rebated.',
            'In Extended session: ',
            '- TOP 1 users, 98% bridging fees (except for gas fees) will be rebated.',
            '- TOP 2 to 8 users, 96% bridging fees (except for gas fees) will be rebated.',
            '- Top 100 shares extend the $7000 prize pool.',
          ],
        },
        {
          label: '4.How to Earn O-Points Rewards?',
          text: [
            'Participants can earn additional event points by completing the following tasks:',
            '- Complete ≥3 transactions for 7 days to earn extra 150 Opoints.',
            '- Complete ≥3 transactions for 14 days to earn extra 450 Opoints.',
            '<span class="orbiter_global_prizes_rule_tag">Note:</span>',
            '- One address can receive a maximum of 450 Opoints.'
          ],
        },
        {
          label: '5.When will the rewards be distributed?',
          text: [
            '- All rewards will be distributed after the event ends.',
            '- Please stay informed and claim your rewards within 3 days of the reward claim portal opening!',
          ],
        },
      ],
    }
  },
}
</script>

<style scoped lang="scss">
.prizes-rule {
  width: 100%;
  margin: 80px 0 200px;
  .rule-title {
    width: 100%;
    font-size: 32px;
    font-weight: 600;
    line-height: 44px;
    letter-spacing: 0px;
    text-align: center;
  }
  .prizes-rule-card {
    padding: 8px 24px 24px;
    width: 100%;
    border: 4px solid rgb(69, 35, 48);
    background: radial-gradient(
        96% 96% at 50% 50%,
        rgba(27, 21, 37, 0) 1.849%,
        rgba(255, 70, 68, 0.2) 100%
      ),
      rgb(18, 4, 30);
    text-align: left;
    margin-top: 16px;
    .card-label {
      margin-top: 16px;
      font-size: 16px;
      font-weight: 600;
      line-height: 28px;
      letter-spacing: 0px;
      font-family: GeneralSans-SemiBold;
      margin-top: 16px;
    }

    .image {
      width: 100%;
      margin-top: 12px;
      img {
        width: 100%;
      }
    }

    .card-rule-text {
      font-size: 14px;
      font-weight: 400;
      line-height: 23px;
      letter-spacing: 0px;
      color: rgba(255, 255, 255, 0.6);
    }
  }
}

@media (max-width: 740px) {
  #prizes-rule {
    width: 100%;
    margin: 32px 0 60px;
    .prizes-rule-card {
      padding: 8px 16px;
    }
    .rule-title {
      font-size: 24px;
    }
  }
}
</style>

// apps/web/app/prizes/components/PrizesRule.tsx
"use client"

import React, { useState } from 'react'
import Image from 'next/image'

import styles from "./PrizesRule.module.css"
import { cn } from '../../../utils/cn'

export default function PrizesRule() {
  const [extendKey, setExtendKey] = useState<number>()

  const rulesArray = [
    {
      title: '1. Which networks are participating in this event?',
      content: [
        <span className='o-prizes-reward o-font-500'> Round 1:</span>,
        <span>Bridge <span className='o-prizes-reward o-font-500'>from specific networks to Eclipse.</span></span>,
        <span> <span className='o-prizes-reward o-font-500' >Specific networks include:</span>Arbitrum、Base、Blast、BNB Chain、BOB、Ethereum、Gravity、Linea、Mode、Morph、Optimism、Polygon、Scroll、Taiko、World Chain、ZKSyncEra、Zora</span>,
        <span>The minimum amount required: ≥0.00055 ETH.</span>,
        <span>Bridge token: ETH</span>,
        <span className='o-prizes-reward o-font-500'> Round 2:</span>,
        <span>Bridge <span className='o-prizes-reward o-font-500'>from specific networks to World Chain or bridge from World Chain to specific networks.</span></span>,
        <span><span className='o-prizes-reward o-font-500'>Specific networks include:</span> Arbitrum、Base、Blast、BNB Chain、BOB、Ethereum、Eclipse、Gravity、IoTeX、Linea、Mode、Morph、Optimism、Polygon、Scroll、Taiko、ZKSyncEra、Zora</span>,
        <span>The minimum amount required: ≥0.00085 ETH.</span>,
        <span>Bridge token: ETH</span>,
        <span className='o-prizes-reward o-font-500'> Round 3:</span>,
        <span>Bridge <span className='o-prizes-reward o-font-500'>from specific networks to Arbitrum or bridge from Arbitrum to specific networks.</span></span>,
        <span><span className='o-prizes-reward o-font-500'>Specific networks include:</span>Polygon、OPBNB、BOB、ZKSyncEra、Manta、Ethereum、Blast、Zora、Optimism、Cyber、Linea、BNB Chain、World Chain、Matchain、Mantle、Scroll、Zircuit、Solana、Mode、Morph、Base、Lisk、Sui</span>,
        <span>Bridge token: ETH、USDC、USDT</span>,
        <span className='o-prizes-reward o-font-500'> Round 4:</span>,
        <span>Bridge <span className='o-prizes-reward o-font-500'>from specific networks to Sui.</span></span>,
        <span><span className='o-prizes-reward o-font-500'>Specific networks include:</span>Taiko、BNB Chain、Base、Optimisim、Arbitrum、 Linea、Polygon、BOB、Ethereum、Scroll、ZKSyncEra</span>,
        <span>Bridge token: USDC</span>,
      ]
    },
    {
      title: '2. What is Orbiter License and how to collect different Orbiter Licenses?',
      content: [
        <span> <span className='o-prizes-reward o-font-500' >Basic Licenses:</span> Complete <span className='o-prizes-reward o-font-500' >≥15 transactions</span> per round. You can collect one Basic License and enter the prize pool for the current round.</span>,
        <span> <span className='o-prizes-reward o-font-500' >Supreme Licenses:</span> Supreme Licenses are only available during specific periods and can only be obtained through <span className='o-prizes-reward o-font-500' >Lucky Draw.</span></span>,
        <span> <span className='o-prizes-reward o-font-500' >Fast Pass:</span> A Fast Pass can directly enter into the Final Prize Pool and can only be obtained through <span className='o-prizes-reward o-font-500' >Lucky Draw.</span></span>,
        <span> <span className='o-prizes-reward o-font-500' >NOTE: </span>Orbiter Licenses can be considered as a voucher for participation in this event and may also serve as a credential for loyal Orbiter users in the future.</span>
      ]
    },
    {
      title: '3. How to Participate in the Lucky Draw?',
      content: [
        <span> Bridge 1 tx to earn 1 entry for the lucky draw. A maximum of 10 entries per address per day.</span>,
        <span> Earn 1 entry for the lucky draw with each transaction. A maximum of 10 entries per address per day.</span>,
        <span> Unused entries do not roll over to the next day.</span>,
        <span> The prize pool includes O-points, Supreme passes, Fast Pass, and $USDC rewards, which may vary at different times. </span>
      ]
    },
    {
      title: '4. How to Enter and Share the Prize Pool?',
      content: [
        <span> Collecting one <span className='o-prizes-reward o-font-500' >Basic License </span> grants eligibility for the prize pool for the current round, which represents 15% of the total prize pool for each round.</span>,
        <span> Gathering <span className='o-prizes-reward o-font-500' >five licenses (including Basic and Supreme licenses)</span> or obtaining one Fast Pass grants entry to the final prize pool, which represents 25% of the total prize pool.</span>,
        <span> <span className='o-prizes-reward o-font-500' >Total Prize Pool Amount:</span> The initial prize pool amount is <span className='o-prizes-reward o-font-500' >$60,000</span> (based on an initial participant count of <span className='o-prizes-reward o-font-500' >10,000</span>). For each additional 1,000 participants over the initial 10,000, the prize pool will increase by $1,200, <span className='o-prizes-reward o-font-500' >up to a maximum limit of $100,000 USDC.</span></span>,
        <span> <span className='o-prizes-reward o-font-500' >Note:</span> During the event period, the top 3 users' (rank by transaction) <span className='o-prizes-reward o-font-500' >96% bridging fees</span> (except for gas fees) will be rebated.</span>
      ]
    },
    {
      title: '5. When will the rewards be distributed?',
      content: [
        <span> O-points rewards will be credited to your Orbiter O-points account within a few minutes.</span>,
        <span> Other rewards will be distributed after the event ends.</span>,
        <span> Please stay informed and claim your rewards within 3 days of the reward claim portal opening!</span>
      ]
    },
    {
      title: '6. The final interpretation rights of the activity are owned by Orbiter Finance.',
      content: [
        <span></span>
      ]
    },
  ]

  const handleExtendClick = (extendIndex: number) => {
    if (extendIndex === extendKey) {
      setExtendKey(undefined)
    } else {
      setExtendKey(extendIndex)
    }
  }


  return (
    <div>
      <h2 className='text-3xl font-semibold text-center mb-8 mt-14 o-font-600'>Terms and Conditions</h2>
      <div className={cn('p-8 border-2 border-[rgba(69,35,48,0.6)] rounded-xl', styles.sectionBgColor)}>
        {rulesArray.map((rule, index) => {
          return (
            <div key={index} className='mt-8 first:mt-0'>
              <div onClick={() => handleExtendClick(index)} className='flex justify-between items-center mt-1 text-base font-semibold leading-6 cursor-pointer'>
                <div className='o-font-500'>{rule.title}</div>
                <Image src="/assets/icon/prizes/extends.svg" style={{ rotate: index === extendKey ? "180deg" : "0deg", willChange: "rotate", transition: "all 0.3s" }} alt="" width={24} height={24} className='w-6 h-6 ml-2' />
              </div>
              <div className='text-sm font-400 leading-7' style={{ display: index === extendKey ? "block" : "none" }}>
                {
                  rule.content.map((option, idx) => {
                    return <p key={idx} className='mt-2 ml-4'>
                      {option}
                    </p>
                  })
                }
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}
